apiVersion: apps/v1
kind: Deployment
metadata:
  name: details
  labels:
    app: fil-rouge
spec:
  replicas: 1
  selector:
    matchLabels:
      app: details
  template:
    metadata:
      labels:
        app: details
    spec:
      containers:
      - name: details
        image: details:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 9080
        livenessProbe:
          httpGet:
            path: /health
            port: 9080
          periodSeconds: 2
          initialDelaySeconds: 0
          failureThreshold: 3
          successThreshold: 1
        readinessProbe:
          httpGet:
            path: /details # sans définition de endpoint /ready, oncheck avec /details
            port: 9080
          periodSeconds: 2
          initialDelaySeconds: 0
          failureThreshold: 3
          successThreshold: 1
---
apiVersion: v1
kind: Service
metadata:
  name: details
spec:
  selector:
    app: details
  ports:
    - protocol: TCP
      port: 9080
      targetPort: 9080