apiVersion: apps/v1
kind: Deployment
metadata:
  name: productpage
  labels:
    app: fil-rouge
spec:
  replicas: 1
  selector:
    matchLabels:
      app: productpage
  template:
    metadata:
      labels:
        app: productpage
    spec:
      containers:
      - name: productpage
        image: productpage:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 9080
        livenessProbe:
          httpGet:
            path: /health
            port: 9080
          periodSeconds: 2
          initialDelaySeconds: 0
          failureThreshold: 3
          successThreshold: 1
        readinessProbe:
          httpGet:
            path: /productpage # sans définition de endpoint /ready, oncheck avec /productpage
            port: 9080
          periodSeconds: 2
          initialDelaySeconds: 0
          failureThreshold: 3
          successThreshold: 1
---
apiVersion: v1
kind: Service
metadata:
  name: productpage
spec:
  selector:
    app: productpage
  type: NodePort
  ports:
    - protocol: TCP
      port: 9080
      targetPort: 9080