apiVersion: apps/v1
kind: Deployment
metadata:
  name: reviews
  labels:
    app: fil-rouge
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reviews
  template:
    metadata:
      labels:
        app: reviews
    spec:
      containers:
      - name: reviews
        imagePullPolicy: IfNotPresent
        image: docker.io/istio/examples-bookinfo-reviews-v2:1.16.2
        livenessProbe:
          httpGet:
            path: /health
            port: 9080
          periodSeconds: 2
          initialDelaySeconds: 0
          failureThreshold: 3
          successThreshold: 1
        readinessProbe:
          httpGet:
            path: /reviews # sans définition de endpoint /ready, oncheck avec /reviews
            port: 9080
          periodSeconds: 2
          initialDelaySeconds: 0
          failureThreshold: 3
          successThreshold: 1

---
apiVersion: v1
kind: Service
metadata:
  name: reviews
spec:
  selector:
    app: reviews
  ports:
    - protocol: TCP
      port: 9080
      targetPort: 9080